language: objective-c
before_install:
  - gem install xcpretty
install: echo
script:
  - export LC_CTYPE=en_US.UTF-8
  - set -o pipefail
  - xcodebuild -workspace JPSimulatorHacksSample.xcworkspace -scheme 'JPSimulatorHacksSample' -sdk iphonesimulator -configuration Debug test | xcpretty -c
